### ISSUE TITLE
Feature request: onSuccess and onError parameters on the LDClient.start method

### ISSUE THREAD

**Issue by NikolajMosbaek** [launchdarkly/ios-client-sdk#126]
It would be very nice if the `- (BOOL)start:(LDConfig *)inputConfig withUserBuilder:(LDUserBuilder *)inputUserBuilder ` method also took 'onSuccess' and 'onError' blocks/closures.

My situation is that I have some code that I want to run AFTER the initial feature flag fetch is done (success or not). Right now I run the code on the four Client delegate methods, but unfortunately there are situations where none of them is called (e.g. if the fetch fails). It also seem like bad practice from my side to assume that any of the delegates are called upon fetch completed. That's why the extra parameters would be very nice to have!

Something like this (forgive me if my syntax is wrong... It's been a while since I last used Objective-C):
`(BOOL)start:(LDConfig *)inputConfig withUserBuilder:(LDUserBuilder *)inputUserBuilder onSuccess:(void(^_Nonnull)(void)) onSuccess onError:(void(^_Nonnull)(NSError* error)) onError`

**Comment by arun251** [comment]
Hi @NikolajMosbaek, we identified some cases where we were not calling the delegate method `serverConnectionUnavailable` on some error conditions. We have fixed that in iOS SDK 2.10.1.

If I'm correct in reading between the lines, it sounds like you are developing in Swift instead of Objective C. We're currently working on a Swift SDK. We would like to add the `onSuccess` and `onError` support in that SDK instead.

**Comment by NikolajMosbaek** [comment]
Hi @arun251,

Great! So I'll update my LD library... 
When do you plan on releasing the Swift SDK?

**Comment by arun251** [comment]
Hi @NikolajMosbaek we expect the Swift SDK to be available in approximately two months from now. Let me know if you'd be interested in a private beta.

**Comment by lwdupont** [comment]
I'd be interested in a private beta @arun251 . For work at Intuit.

**Comment by arun251** [comment]
Hi @NikolajMosbaek and @lwdupont , we have a Swift SDK in beta at 
```
pod 'LaunchDarkly', :git => 'https://github.com/launchdarkly/ios-client.git', :branch => 'v3-beta'
```

Feedback is welcome at support@launchdarkly.com.

**Comment by NiltiakSivad** [comment]
The new Swift SDK does not contain the callbacks requested. The supplied `completionHandler` is a misleading name and not actually reliant on any network requests completing let alone guaranteeing that the feature flags have been returned. At least this as far as I can tell. I'm looking at work arounds using the new `observe` methods.

**Comment by NiltiakSivad** [comment]
In case it helps anyone else, we have a method similar to the following that we call every time our user changes that forces our app to wait for the flags to be returned before proceeding with displaying the UI:

```
    func setUser(_ user: LDUser, completion: @escaping (() -> Void)) {
        // launch darkly allows us to either observe for single key, specified keys or all keys. calling observeAll here will allow us to listen for any flags having been received from their server in order guarantee that flags have been received and thus move forward with our launch sequences.
        launchDarklyClient.observeAll(owner: self) { [weak self] _ in
            self?.flagsFetched(completion: completion)
        }

        // observe unchanged flags here in the case the flags had been properly pulled for the user previously and then restarted the app. If we do not observe for flags unchanged, completion will not be called and unintended consequences with our launch sequences will be observed.
        launchDarklyClient.observeFlagsUnchanged(owner: self) { [weak self] in
            self?.flagsFetched(completion: completion)
        }

        // config is a member variable
        launchDarklyClient.start(config: config, user: user, completion: nil)
    }


    private func flagsFetched(completion: (() -> Void)) {
        launchDarklyClient.stopObserving(owner: self)

        completion()
    }
```

**Comment by torchhound** [comment]
I am closing this issue in light of the observer methods which should provide basic functionality. We have an enhanced Connection Status API in progress which should provide more insight into when flags are received, their state, and any errors encountered.
