### ISSUE TITLE
React Native Build Issues

### ISSUE THREAD

**Issue by BG687** [launchdarkly/ios-client-sdk#166]
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/) and clicking "submit a request", or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
Having issues building React Native app in XCode 10.1. Followed the steps in the SDK reference here: https://docs.launchdarkly.com/docs/react-native-sdk-reference

The errors that XCode is throwing include:

`missing required module 'SwiftShims'` (Launch Darkly RN Client)

`Command MergeSwiftModule failed` (Launch Darkly)

**To reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
The version of this SDK that you are using.

3.0.0-beta.2 & 3.0.0-beta.3

**Language version, developer tools**
For instance, Go 1.11 or Ruby 2.5.3. If you are using a language that requires a separate compiler, such as C, please include the name and version of the compiler too.

**OS/platform**
For instance, Ubuntu 16.04, Windows 10, or Android 4.0.3. If your code is running in a browser, please also include the browser type and version.

Trying to build for iPhone simulator

**Additional context**

**Comment by BG687** [comment]
Without the additional copy: 

I'm having issues building React Native app in XCode 10.1. Followed the steps in the SDK reference here: https://docs.launchdarkly.com/docs/react-native-sdk-reference

The errors that XCode is throwing include:

missing required module 'SwiftShims' (Launch Darkly RN Client)

Command MergeSwiftModule failed (Launch Darkly)

**Comment by torchhound** [comment]
@BG687 Based on further comments in the React Native client repo is this issue resolved?
