### ISSUE TITLE
Warnings when building with Xcode 10.2

### ISSUE THREAD

**Issue by simonliotier** [launchdarkly/ios-client-sdk#167]
Hi,

We are using CocoaPods to integrate LaunchDarkly in our app. When building with Xcode 10.2, we get 14 warnings such as 
`.../Pods/LaunchDarkly/Darkly/NSDictionary+LaunchDarkly.h:9:56: Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)`.

![Xcode10_2](https://user-images.githubusercontent.com/359843/55235723-7f58a580-522e-11e9-8faf-dcc93eaf9f48.png)

These warnings are displayed even if we are using the `inhibit_all_warnings!` flag in our Podfile, because the code causing the warning is in header files, and the flag does not work with header files (see [this issue](https://github.com/CocoaPods/CocoaPods/issues/5589) for more details).

Could you fix this warnings?

**SDK version**
- DarklyEventSource (4.0.1)
- LaunchDarkly (2.14.4)

**Language version, developer tools**
- Xcode 10.2
- Swift 5

**Comment by MikeLeber117** [comment]
same for us as well

**Comment by rbaumbach** [comment]
I'm seeing this issue as well.

**Comment by SuperMarioBean** [comment]
same here

**Comment by rbaumbach** [comment]
@simonliotier You can point to my GitHub repo in your `Podfile` until my changes make it into the next version of of the `ios-client` if you'd like.

**Comment by torchhound** [comment]
We added nullability type specifiers in 3.0.0
