### ISSUE TITLE
Crash in LDEventTrackingContext: Unrecognized Selector (v3.0.0)

### ISSUE THREAD

**Issue by JUSTINMKAUFMAN** [launchdarkly/ios-client-sdk#173]
**Is this a support request?**
Yes.

**Describe the bug**
We have experienced several crashes on iOS over the last week on release v3.0.0 of the SDK.

It is not clear whether they are all related, however I am attaching the details we have here from our logs for all 3 crash types below.

**To reproduce**
I have observed the first type of crash (see 1 below) running on simulator, but have been unable to establish consistent steps for reproducing it. Possibly a race condition?

**Expected behavior**
Not to crash...

**Logs**
1. `NSInvalidArgumentException | -[LDEventTrackingContext objectForKeyedSubscript:]: unrecognized selector sent to instance`

2. `isEqual: | featuresJsonDictionary | count | flagValueForFlagKey: | containsFlagKey: | addObject: | countByEnumeratingWithState:objects:count:`

3. `addObject: | count | featuresJsonDictionary | countByEnumeratingWithState:objects:count: | containsFlagKey: | flagValueForFlagKey: | isEqual:`

**SDK version**
v3.0.0

**Language version, developer tools**
Swift 5.0.1

**OS/platform**
iOS 12.2

**Additional context**
N/A

**Comment by bwoskow-ld** [comment]
Hi Justin,

Thanks for reaching out. We see that you've also filed a request with our support team. Let's consolidate our conversation onto that request.

Ben
