### ISSUE TITLE
Ambiguous access level

### ISSUE THREAD

**Issue by wqz-leo** [launchdarkly/ios-client-sdk#184]
**Is your feature request related to a problem? Please describe.**

[This initialiser](https://github.com/launchdarkly/ios-client-sdk/blob/v4/LaunchDarkly/LaunchDarkly/Models/LDConfig.swift#L91) is private, but the struct and properties are public. Therefore, this struct cannot be created from outside of this package, and those two properties are not accessible. There might be a reason of this, but from a developer point of view it's a bit confusing.

**Describe the solution you'd like**
Make initialiser public or struct and properties internal.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by torchhound** [comment]
Hi @wqz-leo, thanks for bringing this up! How are you using `Minima`? Are you using the `struct` directly or using the `public` field in the `LDConfig` class? Is your usecase what's defined in the [migration guide](https://github.com/launchdarkly/ios-client-sdk/blob/62806eaecd0d67c12fe24cc5058dee7284663d7c/MigrationGuide.md#minima) or something different?

**Comment by wqz-leo** [comment]
Hi @torchhound , sorry my bad, I was play around with the library and confused initially. Now I figured out the reason for this. Thanks for reply.
