### ISSUE TITLE
Evaluation reasons / VariationDetail support of iOS client

### ISSUE THREAD

**Issue by mc7h** [launchdarkly/ios-client-sdk#190]
**Describe the solution you'd like**
https://docs.launchdarkly.com/docs/evaluation-reasons

**Comment by torchhound** [comment]
Hi @mc7h, thanks for the feature request! It's on the roadmap along with other improvements to the iOS client SDK.

**Comment by drommk** [comment]
Hi, this is really cool insight and we'd like to have this as well, any ETA for this?

**Comment by torchhound** [comment]
Hi @drommk thanks for letting us know that you're interested, I can't give you a more specific ETA right now.

**Comment by torchhound** [comment]
Hi @drommk and @mc7h, Evaluation Reasons are now available in iOS 4.3.0!
