### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by fchauvin** [launchdarkly/ios-client-sdk#191]
**Describe the solution you'd like**
Now that Xcode 11 includes first-class support for SPM dependencies, it would be great to add support for that. Once Xcode 11 is no longer in beta, I believe that many Carthage/Cocoapod users are going to want to migrate to it, myself included!

**Comment by bwoskow-ld** [comment]
Thanks for the suggestion, @fchauvin. We'll keep this under consideration for the future.

**Comment by claudiogomezGL** [comment]
Hi @bwoskow-ld, is there any change this can be included in a near future?

**Comment by bwoskow-ld** [comment]
Hi @claudiogomezGL -- while this improvement is on our backlog, we can't commit to a specific timeframe at this time.

**Comment by MadsBogeskov** [comment]
I need this as well. Would be awesome to add :)

**Comment by jboisjo** [comment]
Any updates?

**Comment by kemalenver** [comment]
+1 for this.  2/10 libs we use don't support the package manager.  Would be great to knock you off the list :)

**Comment by allanscofield** [comment]
Any news?

**Comment by tomjcohen** [comment]
Evaluating LD right now (on the 30d trial) — really hope SPM support is on the roadmap soon.

**Comment by john-crossley** [comment]
Any news on this? 🤔

**Comment by gwhelanLD** [comment]
Hi everyone,

I'm happy to announce that the 5.0.1 release of the iOS SDK has support for the Swift Package Manager. Some resources on this release's changes are available in:
* [The release's change notes](https://github.com/launchdarkly/ios-client-sdk/releases/tag/5.0.1).
* [The migration guide](https://docs.launchdarkly.com/sdk/client-side/ios/migration-4-to-5).
* And [the iOS SDK reference guide](https://docs.launchdarkly.com/sdk/client-side/ios).

Thank you all for your patience and support on this issue,
@gwhelanLD
