### ISSUE TITLE
Tag version2.5.1.1 is causing issues in carthage update

### ISSUE THREAD

**Issue by jazz-mobility** [launchdarkly/ios-client-sdk#192]
**Describe the bug**
As `ios-client-sdk` is not using correct semantic versioning, I am facing issues in Carthage update.

**To reproduce**
Update from a very old version of SDK to latest

**Expected behavior**
Correct version of SDK should be selected during carthage update

**Logs**
my cart file - `github "launchdarkly/ios-client" == 4.1.2`
Logs from crathage - `*** Checking out ios-client at "version2.5.1.1"`

**SDK version**
4.1.2

**Language version, developer tools**
Xcode 10.3, carthage 0.33

**OS/platform**
macOS mojave 10.14.5

**Additional context**
I see there are some other tags which are not following semantic versioning, those can also cause issues.

**Comment by bwoskow-ld** [comment]
Hi @jazz-mobility ,

Are you updating from `version2.5.1.1` of `ios-client`? If so, perhaps you can manually update your cart file to version `2.5.1` and from there update to `4.1.2`? Let me know if that helps.

Although "2.5.1" should be semantically earlier than a "2.5.1.1" release, it appears that it is actually two days newer: https://github.com/launchdarkly/ios-client-sdk/tags?after=2.6.0.2 🤷‍♂

**Comment by jazz-mobility** [comment]
@bwoskow-ld 
old version - `github "launchdarkly/ios-client" == 2.13.9`
new version i am trying to update `github "launchdarkly/ios-client-sdk" == 4.1.2`
However If i point it to specific tag then it works. e.g. `github "launchdarkly/ios-client-sdk"  "4.1.2"`

**Comment by torchhound** [comment]
Hi @jazz-mobility, it sounds like you were able to update so I'm going to close this issue. Please feel free to ask us further questions here or reach out to support.
