### ISSUE TITLE
Error when install via Cocoapods. "Could not build Objective-C module 'DarklyEventSource'

### ISSUE THREAD

**Issue by clehew** [launchdarkly/ios-client-sdk#193]
**Describe the bug**
I am unable to use the Launch Darkly pod because when I try to build my project I see this:

> error: 'DarklyEventSource/LDEventSource.h' file not found
> #import <DarklyEventSource/LDEventSource.h>
>         ^
> <unknown>:0: error: could not build Objective-C module 'DarklyEventSource'
> <module-includes>:2:9: note: in file included from <module-includes>:2:
> #import "Headers/LaunchDarkly-Swift.h"

To fix this I have cleared derived data, removed all pods and reinstalled the pod as the only pod in my project.  I cannot seem to find a way to get past this error. 

**To reproduce**
Just did a pod install. 

**Expected behavior**
Launch Darkly should be installed and my project should build. 

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
 pod 'LaunchDarkly', '4.1.2'

**Language version, developer tools**
Xcode 10.3
Swift 5

**OS/platform**
iOS 10.0 is our deployment target

**Additional context**
At first I assumed this was a random Cocoapods error, but after uninstalling the pods and reinstalling, I can't seem to fix this.  Any insight would be helpful.

**Comment by torchhound** [comment]
Hi @clehew, are you upgrading from an older version of our SDK? Is there a version that did work correctly for you?

**Comment by clehew** [comment]
@torchhound  -Since you asked, I tried to downgrade to 4.0.0 because originally it worked with that version, it doesn't work now unfortunately.  This issue started showing up around the time when I upgraded to 4.1.2 and Xcode 10.3.

**Comment by clehew** [comment]
@torchhound  we can close this.  It was some kind of Cocoapods issue.  I deleted my project, deleted derived data, re-cloned it and did pod install and now it works.

**Comment by torchhound** [comment]
Glad to hear it's working now!

**Comment by torchhound** [comment]
Hi @clehew sorry to hear this is happening again. I'll try and investigate but this sounds like it might be specific to your environment somehow.

**Comment by clehew** [comment]
@torchhound maybe so, best I can tell it may have something to do with the mix of Swift and Objective-C.  I'm getting it almost everyday, I'll try and get some steps to recreate if possible.

**Comment by gwhelanLD** [comment]
As this issue hasn't had any recent activity, and the iOS SDK has moved to a new Swift EventSource implementation, I'm closing this issue.

Thanks for working with us on this issue,
@gwhelanLD
